# ==============================================================================
# DiscoveryLastFM Development Docker Compose Override
# Use with: docker compose -f docker-compose.yml -f docker-compose.dev.yml up
# ==============================================================================

version: '3.8'

services:
  
  # Development overrides for main application
  discoverylastfm:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime  # Use runtime stage for faster builds
    
    # Development environment
    environment:
      - DISCOVERY_MODE=test        # Test mode for development
      - DEBUG=true                 # Enable debug logging
      - DRY_RUN=true              # Safe testing mode
      - PYTHONUNBUFFERED=1        # Real-time log output
    
    # Development volumes - mount source code if available
    volumes:
      - config:/app/config
      - logs:/app/logs
      - cache:/app/cache
    
    # Override command for interactive development
    command: ["python", "/app/DiscoveryLastFM.py"]
    
    # Add development ports
    ports:
      - "8080:8080"   # Health check/debug port
    
    # Development resource limits (more permissive)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 64M

  # Development Redis with exposed ports for debugging
  redis:
    ports:
      - "6379:6379"
    
    # Development command (less restrictive)
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru

  # Development log viewer
  logs:
    image: amir20/dozzle:latest
    container_name: discoverylastfm-logs
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    ports:
      - "8081:8080"
    
    networks:
      - discoverylastfm
    
    environment:
      - DOZZLE_LEVEL=debug
      - DOZZLE_FILTER="name=discoverylastfm*"
    
    labels:
      - "com.discoverylastfm.service=dev-logs"